version: 2.1
orbs:
  codecov: codecov/codecov@1.0.5
jobs:
  build:
    docker:
      - image: cimg/go:1.18

    environment:
      TEST_RESULTS: /tmp/test-results

    steps:
      - checkout
      - run: mkdir -p $TEST_RESULTS

      - restore_cache:
          keys:
            - go-mod-v4-{{ checksum "go.sum" }}

      - run:
          name: Run unit tests
          command: |
            PACKAGE_NAMES=$(go list ./... | circleci tests split --split-by=timings --timings-type=classname)
            gotestsum --junitfile ${TEST_RESULTS}/gotestsum-report.xml -- $PACKAGE_NAMES
            go test -timeout 10s -p 4 -count=1 ./... -v -covermode=count -coverprofile=coverage.out
            go tool cover -html=coverage.out -o coverage.html
            mv coverage.html /tmp/test-results

      - run:
          name: Run linters
          command: make lint

      - run:
          name: Run vuln checks
          command: make vuln

      - save_cache:
          key: go-mod-v4-{{ checksum "go.sum" }}
          paths:
            - "$HOME/go/pkg/mod"

      - store_artifacts:
          path: /tmp/test-results
          destination: raw-test-output

      - store_test_results:
          path: /tmp/test-results
      - codecov/upload:
          file: coverage.out

workflows:
  version: 2
  build-workflow:
    jobs:
      - build:
          context: SONAR_TOKEN
